<template>
  <div id="app">
    <loading :active.sync="isLoading" 
        :can-cancel="true"
        :is-full-page="fullPage"
        :background-color="bg"
        :opacity="1">
      <div class="loadingio-spinner-ripple-3dtrjjsu7xa"><div class="ldio-axavq2xq5ul">
      <div></div><div></div>
      </div></div>
    </loading>
    <go-top :size="50"></go-top>
    <router-view v-model="fullPage"></router-view>
  </div>
</template>

<script>
import GoTop from '@inotom/vue-go-top';
export default {
  name: 'App',
  data(){
    return{
      isLoading: true,
      fullPage: true,
      bg: '#b9cd94'
    }
  },
  components: {
    GoTop
  },
  mounted(){
    setTimeout(() => {
      this.isLoading = false;
      this.fullPage = false;
    },2000)
  }
}
</script>

<style lang="scss">
@import './assets/css/all.css';
#app {
  /* font-family: Avenir, Helvetica, Arial, sans-serif; */
  font-family: PingFangTC,Microsoft JhengHei,Helvetica Neue,Helvetica,Arial,sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #585858;
  background: #f4f6e3;
}
.vue-go-top:focus{
  outline: none;
  box-shadow: none;
}

/* generated by https://loading.io/ */
@keyframes ldio-axavq2xq5ul {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 18px;
    left: 18px;
    width: 156px;
    height: 156px;
    opacity: 0;
  }
}

.ldio-axavq2xq5ul div {
  position: absolute;
  border-width: 4px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-axavq2xq5ul 1s cubic-bezier(0,0.2,0.8,1) infinite;
}

.ldio-axavq2xq5ul div:nth-child(1) {
  border-color: #fffffc
}

.ldio-axavq2xq5ul div:nth-child(2) {
  border-color: #f1f2f3;
  animation-delay: -0.5s;
}

.loadingio-spinner-ripple-3dtrjjsu7xa {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-axavq2xq5ul {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-axavq2xq5ul div { box-sizing: content-box; }
</style>
